stages:
  - code-linting

variables:
  ALUMNO: 85505-85829-92425
  TAG: devops-runner

code-lint-python:
  image: python:3.10
  stage: code-linting
  tags:
    - $TAG
  variables:
    ARTIFACT_FILE_NAME: python-code-linting-$ALUMNO.txt
  script:
    - python3 -m venv venv
    - pip install --upgrade pip
    - source venv/bin/activate
    - pip install pylint
    - chmod 700 ./run_pylint.sh
    - ./run_pylint.sh > $ARTIFACT_FILE_NAME
  artifacts:
    paths:
      - $ARTIFACT_FILE_NAME

code-lint-node:
  image: node:18
  stage: code-linting
  tags:
    - $TAG
  variables:
    ARTIFACT_FILE_NAME: node-api-linting-$ALUMNO.txt
  script:
    - cd api-node
    - npm install
    - npm install eslint
    - chmod 700 ./run_eslint.sh
    - ./run_eslint.sh > $ARTIFACT_FILE_NAME
  artifacts:
    paths:
      - $ARTIFACT_FILE_NAME
