version: '3.8'
name: 12-docker-compose

services:

  nginx-users:
    build: nginx/
    ports:
      - "8080:80"
    networks:
      - crud-users-net
    restart: always
    links:
      - api-crud-users:api-crud-users

  api-crud-users:
    build: api/
    networks:
      - crud-users-net
    depends_on: 
      - db-crud-users
    environment:
      - MYSQL_DATABASE_USER=testuser
      - MYSQL_DATABASE_PASSWORD=testpass
      - MYSQL_DATABASE_DB=utn
      - MYSQL_DATABASE_HOST=db-crud-users
    links:
      - "db-crud-users:db-crud-users"

  api-node:
    build: api-node/
    networks:
      - crud-users-net

  db-crud-users:
    build: db/
    restart: always
    networks:
      - crud-users-net
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: utn
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass

  react-front:
    build: web/
    networks:
      - front-net
    ports:
      - "3000:80"

volumes:
  data:

networks:
  crud-users-net:
  front-net: