version: '3.8'

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    image: bd-crud-users:latest
    container_name: db-crud-users
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: utn
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - db-crud-users-data:/var/lib/mysql
    networks:
      - crud-users-net
    restart: always

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: api-crud-users:latest
    container_name: api-crud-users
    ports:
      - "5000:5000"
    networks:
      - crud-users-net
    restart: always

networks:
  crud-users-net:
    driver: bridge

volumes:
  db-crud-users-data:
    driver: local
