services:

  nginx-users:
    image: registry-alumnos.labsis.frc.utn.edu.ar:8443/nginx-users-85505-85829-92425:latest
    build: nginx/
    ports:
      - "8080:80"
    networks:
      - crud-users-net
    restart: always
    links:
      - api-crud-users:api-crud-users

  api-crud-users:
    image: registry-alumnos.labsis.frc.utn.edu.ar:8443/api-crud-users-85505-85829-92425:latest
    build: api/
    networks:
      - crud-users-net
    depends_on: 
      - db-crud-users
    environment:
      - MYSQL_DATABASE_USER=${MYSQL_USER}
      - MYSQL_DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE_DB=${MYSQL_DATABASE}
      - MYSQL_DATABASE_HOST=db-crud-users
    links:
      - "db-crud-users:db-crud-users"

  api-node:
    image: registry-alumnos.labsis.frc.utn.edu.ar:8443/api-node-85505-85829-92425:latest
    build: api-node/
    networks:
      - crud-users-net

  db-crud-users:
    image: registry-alumnos.labsis.frc.utn.edu.ar:8443/db-crud-users-85505-85829-92425:latest
    build: db/
    restart: always
    networks:
      - crud-users-net
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  react-front:
    image: registry-alumnos.labsis.frc.utn.edu.ar:8443/react-front-85505-85829-92425:latest
    build: web/
    networks:
      - front-net
    ports:
      - "3000:80"

volumes:
  data:

networks:
  crud-users-net:
  front-net: